---
- name: Create EC2 Instance
  hosts: localhost  # This playbook doesn't target any remote hosts but runs on the local machine.

  vars:
    region: us-east-1   
    instance_type: t2.micro
    ami_id: ami-0874ff0d73a3ab8cf  
    key_name: kk   
    security_group_ids:
      - sg-08173ecf77d5d8f2a  
    subnet_id: subnet-0cf80e89b2ea638f8  
    count: 1

  tasks:
    - name: Launch EC2 Instance
      community.aws.ec2:
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        security_group: "{{ security_group_ids }}"
        subnet_id: "{{ subnet_id }}"
        count: "{{ count }}"
        wait: yes
      register: ec2_instance

    - name: Display EC2 Instance Information
      debug:
        var: ec2_instance
