---
- name: to install httpd and ensure apache is running
  hosts: group
  become: yes
  tasks:
    - name: installation of httpd
      yum:
       name: httpd
       state: latest
    - name: ensure apache is running
      service:
        name: httpd
        state: started
    - name: Copy file to a remote machine
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
        force: yes
    - name: Ensure the default Apache port is 8080
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80'
        insertafter: '^#Listen '
        line: Listen 81   
    - name: ensure apache is running
      service:
        name: httpd
        state: restarted
    - name: To check the outp
      shell:
         cmd: curl localhost:81 > /tmp/output