---
- name: Create EC2 Instance
  hosts: localhost  # This playbook doesn't target any remote hosts but runs on the local machine.
  connection: local
  tasks:
  - name: launching ec2  
    ec2:
      aws_access_key: AKIA3TW4ZE5K7X6AABEM
      aws_secret_key: 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
      region: ap-south-1
      instance_type: t2.micro
      image: ami-008b85aa3ff5c1b02
      key_name: "Ansible_key"
      group: default
      instance_tags:  
        Name: Demo_server
      vpc_subnet_id: subnet-080b5433662bbccba 
      count: 1


  
